name: twitch_api
description: A wrapper in pure Dart to connect to Twitch.tv using OAuth implicit
  authentication.
version: 0.6.1
homepage: https://github.com/TesteurManiak/twitch_api_flutter
repository: https://github.com/TesteurManiak/twitch_api_flutter

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: ^4.0.6

dev_dependencies:
  http_mock_adapter: ^0.3.3
  lint: ">=1.10.0 <3.0.0"
  test: ^1.21.4

false_secrets:
  - /test/**
