name: twitch_api
description: A wrapper in pure Dart to connect to Twitch.tv using OAuth implicit
  authentication.
version: 0.7.0
repository: https://github.com/TesteurManiak/twitch_api_flutter
issue_tracker: https://github.com/TesteurManiak/twitch_api_flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.2
  coverage: ^1.6.3
  fd_lints: ">=1.0.2 <3.0.0"
  freezed: ^2.3.3
  http_mock_adapter: ">=0.4.4 <0.7.0"
  json_serializable: ^6.6.2
  mocktail: ">=0.3.0 <2.0.0"
  remove_from_coverage: ^2.0.0
  test: ^1.24.2

false_secrets:
  - /test/**
