name: twitch_api
description: A wrapper in pure Dart to connect to Twitch.tv using OAuth implicit
  authentication.
version: 0.5.0
homepage: https://github.com/TesteurManiak/twitch_api_flutter
repository: https://github.com/TesteurManiak/twitch_api_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0

dev_dependencies:
  coverage: ^1.0.3
  http_mock_adapter: ^0.3.2
  lint: ^1.5.3
  test: ^1.17.5
